### ISSUE TITLE
Add CoreDNS configmap to argo

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-argocd-manifests#52]
We will have to use some argocd ignore jsonpath annotations to ignore automated parts of the configmap.

**Comment by chuckbelisle** [comment]
Note from the a quick discussion with @blairdrummond 

> Blair Drummond: I think this would be a good introductory issue for Pat

https://github.com/StatCan/aaw-argocd-manifests/issues/52

GitHubGitHub
Add CoreDNS configmap to argo · Issue #52 · StatCan/aaw-argocd-manifests

> We will have to use some argocd ignore jsonpath annotations to ignore automated parts of the configmap. (92 kB)
> https://github.com/StatCan/aaw-argocd-manifests/issues/52

```
# kubectl get cm -n kube-system coredns-custom -o yaml | yq -P e -
apiVersion: v1
data:
  ingress.override: |
    rewrite name vault.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name vetting.aaw-dev.cloud.statcan.ca istio-ingressgateway-protected-b.istio-system.svc.cluster.local
    rewrite name minio-gateway-standard-system-boathouse.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name console-minio-gateway-standard-system-boathouse.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name minio-gateway-premium-system-boathouse.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name minio-gateway-standard-ro-system-boathouse.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name minio-gateway-premium-ro-system-boathouse.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name minio-standard.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name minio-premium.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
    rewrite name max-object-detector.christian-ritter.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
  kfserving-ingress.override: |
    rewrite name max-object-detector.will-hearn.aaw-dev.cloud.statcan.ca istio-ingressgateway.istio-system.svc.cluster.local
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-06T23:29:08Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
  name: coredns-custom
  namespace: kube-system
  resourceVersion: "417247217"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns-custom
  uid: 74838b77-f59e-41f3-86c6-6bb06f3d4d1b
```

> You can use this:
> https://tost.dev/blog/ignore_differences_in_argocd/

`ignoreDifferences:`

> To ignore `kfserving-ingress.override` , which is important because that is controlled by a controller, not argocd
> 
> Blair Drummond:coffee: It's important for artifactory stuff I think. Atm I'm making changes to this manually

**Comment by chuckbelisle** [comment]
@vexingly see comments above, let me and/or @blairdrummond if you have any questions

**Comment by vexingly** [comment]
The ignoreDifferences syntax is simple enough to add, we would need to do some testing to get the expression right, some questions:

- Is there a specific Application resource that this needs to be added to / which could be used for testing?
- We want to ignore the existence of kfserving-ingress.override or only the content?
- Do we want to ignore ingress.overrride or all of .data ?

Since .data is not an array/list it looks like it might be more difficult to ignore one element, I believe this expression would only ignore the content of kfserving-ingress.override for instance:

`apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      namespace: kube-system
      jsonPointers:
        - /data/kfserving-ingress.override`

Alternative to jsonPointer would be to try:
`    jqPathExpressions:
    - .data.kfserving-ingress\.override`

**Comment by blairdrummond** [comment]
Hmm you might be able to use a jq path expression

https://github.com/argoproj/argo-cd/pull/6109/files#diff-b169c017f498a7143a6cc4744c396734a6c98b87b3a537f8af4ebb2fd7a2c1d6R22

It might support something like "ignore all fields other than X"

in any case, I'd just merge a PR it into Dev **With auto-sync off** and you'll be able to see the diff in ArgoCD. It's pretty safe to test on Dev.

**Comment by vexingly** [comment]
https://daaas-system-argocd.aaw-dev.cloud.statcan.ca/applications/kube-system?operation=false&resource=

So deployed to dev and argocd is ignoring the kfserving-ingress.override key, which it expects to be blank but currently has a value, this is what we want?

The only issue is that if it does sync for any reason it will wipe out that field...

**Comment by vexingly** [comment]
@blairdrummond its a bit ugly but seems to be working (minor formatting issues, I don't believe impacts the functionality?):

https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/kube-system/coredns-custom.jsonnet
https://daaas-system-argocd.aaw-dev.cloud.statcan.ca/applications/kube-system?operation=false&resource=

It's on self-heal currently with that jsonnet!

**Comment by blairdrummond** [comment]
Done!
