### ISSUE TITLE
Look into Jsonnet, Kustomize, etc, as options

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-argocd-manifests#7]
Look into best tools/approaches for managing the Dev/Prod split.

https://argo-cd.readthedocs.io/en/stable/user-guide/application_sources/

My personal view at the moment is that jsonnet does the best job of managing configuration differences between dev and prod environments. It allows conditionals based on which branch your code is executing in, which allows logic like [this](https://github.com/StatCan/aaw-argocd-manifests/blob/c865c553fd5033906d8ede4c2ea4541d05d9e38d/statcan-system/authenticated-gateway/ingresses.jsonnet#L4-L8), which is much more involved using kustomize.

Jsonnet *does* introduce json rather than yaml, which sucks, but this seems like it [will be resolved shortly](https://github.com/google/jsonnet/issues/925#issuecomment-885285445). Once this is in, the jsonnet files will look a lot like yaml files, but with the option to conditionally modify variables.

CC @sylus @zachomedia @brendangadd

**Comment by sylus** [comment]
We had this discussion so think we are good ^_^
